# Generated by Django 5.2.5 on 2025-08-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_pricehistory_remove_wallet_is_virtual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
